# -*- coding: utf-8 -*-
"""21201128_zannatun_tazree_tisha_A3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15MAAGROR1oCmNhVoFLYmKIubjkNyJj3c
"""

############### task 1 ############
def utility(gen, tar, wei):
 max_len=max(len(gen), len(tar))
 total=0
 for i in range(max_len):
  if i < len(wei):
      w= wei[i]
  else:
      w= 1
  if i < len(gen):
      g_val= ord(gen[i])
  else:
      g_val= 0
  if i < len(tar):
      t_val= ord(tar[i])
  else:
      t_val= 0
  diff= abs(g_val - t_val)
  total+= (w * diff)
 return -total

def minimax(pool, tar, wei, maximizing, A, B, dept, seq):
 if not pool:
  u= utility(seq, tar, wei)
  return (u, seq)
 if maximizing:
  bestSeq= float('-inf')
 else:
  bestSeq= float('inf')
 best_seq= None

 for i, ncleo in enumerate(pool):
  new_pool= pool[:i] + pool[i+1:]
  new_seq= seq + ncleo
  u, result_seq= minimax(new_pool, tar, wei, not maximizing, A, B, dept + 1, new_seq)
  if maximizing:
   if u > bestSeq:
    bestSeq= u
    best_seq= result_seq
   A = max(A, bestSeq)
  else:
   if u < bestSeq:
    bestSeq= u
    best_seq= result_seq
   B = min(B, bestSeq)
  if B <= A:
      break
 return bestSeq, best_seq

def t1(pool_str, tar_str, id):
  pool= []
  for x in pool_str.split(','):
    pool.append(x.strip())
  tar= tar_str
  wei= list(map(int, id[-len(tar):]))
  (u, seq) = minimax(pool, tar, wei, True, float('-inf'), float('inf'), 0, '')
  return (seq, u)


pool_input = "A,T,C,G"
tar_input = "ATGC"
sid_input = [2, 1, 2, 0, 1, 1, 2, 8]
best_seq, util = t1(pool_input, tar_input, sid_input)
print("Best gene sequence genrated:", best_seq)
print("uility score:", util)

############### task 2 ############
def utility(gen, tar, wei):
 max_len=max(len(gen), len(tar))
 total=0
 for i in range(max_len):
  if i < len(wei):
      w= wei[i]
  else:
      w= 1
  if i < len(gen):
      g_val= ord(gen[i])
  else:
      g_val= 0
  if i < len(tar):
      t_val= ord(tar[i])
  else:
      t_val= 0
  diff= abs(g_val - t_val)
  total+= (w * diff)
 return -total

def minimax(pool, tar, wei, maximizing, A, B, dept, seq):
 if not pool:
  u= utility(seq, tar, wei)
  return (u, seq)
 if maximizing:
  bestSeq= float('-inf')
 else:
  bestSeq= float('inf')
 best_seq= None

 for i, ncleo in enumerate(pool):
  new_pool= pool[:i] + pool[i+1:]
  new_seq= seq + ncleo
  u, result_seq= minimax(new_pool, tar, wei, not maximizing, A, B, dept + 1, new_seq)
  if maximizing:
   if u > bestSeq:
    bestSeq= u
    best_seq= result_seq
   A = max(A, bestSeq)
  else:
   if u < bestSeq:
    bestSeq= u
    best_seq= result_seq
   B = min(B, bestSeq)
  if B <= A:
      break
 return bestSeq, best_seq

def t2(pool_str, tar_str, id):
  pool = []
  tar = tar_str
  wei = []
  new_wei = []
  for x in pool_str.split(','):
    pool.append(x.strip())
  for y in id[-len(tar):]:
    wei.append(int(y))
  fst = str(id[0])
  snd = str(id[1])
  two_digit = int(fst + snd)
  boost = (two_digit / 100)
  new_wei = wei + [float(boost)]
  (uti, seq) = minimax(pool, tar, wei, True, float('-inf'), float('inf'), 0, '')
  pool_S = pool + ['S']
  boost_uti, boost_seq = minimax(pool_S, tar, new_wei, True, float('-inf'), float('inf'), 0, '')
  if boost_uti > uti:
    feed = "YES"
  else:
    feed = "NO"
  return feed, boost_seq, boost_uti
pool_input = "A,T,C,G"
tar_input = "GCAT"
id= [2, 1, 2, 0, 1, 1, 2, 8]
(feed, boosted_seq, boosted_u) = t2(pool_input, tar_input, id)
print(feed)
print("With special nucleotide")
print(f"Best gene sequence generated: {boosted_seq}, utility score: {boosted_u}")