# -*- coding: utf-8 -*-
"""Group_ 04_21201128_24301568.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTxhiNLRV5awe4_ANwMYZpPH8kuRIUvH

## **Setup & Dataset Loading**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# Load dataset
df = pd.read_csv('/content/telco_customer_churn.csv')
df = df.drop('customerID', axis=1)
print("Shape:", df.shape)
print("Data Types:\n", df.dtypes)

"""# **Data Cleaning**"""

# Clean TotalCharges
df['TotalCharges'] = df['TotalCharges'].replace(['NULL', 'null', 'NaN', 'N/A', '', ' '], np.nan)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].mean())
print("Missing values per column:\n", df.isnull().sum())

"""# **Exploratory Data Analysis**


"""

# Churn distribution
plt.figure(figsize=(6,6))
df['Churn'].value_counts().plot.pie(autopct='%1.1f%%')
plt.title('Churn Distribution')
plt.show()

# Separate numerical & categorical featuress
numerical_datas = df.select_dtypes(include='number')
categorical_datas = df.select_dtypes(include='object')

numerical_featuress=numerical_datas.columns.tolist()
print(f'There are {len(numerical_featuress)} numerical featuress:', '\n')
print("Numerical featuress:", list(numerical_datas.columns), '\n')
categorical_featuress=categorical_datas.columns.tolist()
print(f'There are {len(categorical_featuress)} categorical featuress:', '\n')
print("Categorical featuress:", list(categorical_datas.columns))

# Histograms for numerical features
numerical_datas.hist(figsize=(12,10), bins=20)
plt.tight_layout(); plt.show()

# Bar plots for categorical features
for col in categorical_datas.columns:
    categorical_datas[col].value_counts().sort_index().plot(kind='bar', rot=0)
    plt.title(f'Distribution of {col}')
    plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

#Encode categorical variables
label_encoders = {}
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

for col in categorical_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

correlation_matrix = df_encoded.corr()

#heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix,annot=True,
            cmap='coolwarm',fmt='.2f',
            linewidths=0.5,center=0,
            square=True)
plt.title('Feature Correlation Heatmap (All Features)', fontsize=16, pad=20)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Density plot of numerical features
numerical_datas.plot(kind='density', subplots=True, layout=(3, 2), figsize=(12, 10), sharex=False)
plt.suptitle("Density Plot of Numerical Features", fontsize=16)
plt.show()

"""# **Encoding & Scaling**"""

from sklearn.preprocessing import LabelEncoder, RobustScaler

df_encoded = df.copy()

#Encode categorical
label_encoders = {}
for col in categorical_datas.columns:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

# Scale numerical
num_cols = ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']
scaler = RobustScaler()
df_encoded[num_cols] = scaler.fit_transform(df_encoded[num_cols])

# Fill the remaining Nals
df_encoded[num_cols] = df_encoded[num_cols].fillna(df_encoded[num_cols].median())
for col in categorical_datas.columns:
    df_encoded[col] = df_encoded[col].fillna(df_encoded[col].mode()[0])

"""# **Missing Values Heatmap**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.heatmap(df.isnull(),
            cbar=False,
            cmap="viridis",  # yellow = missing, purple = not missing
            yticklabels=False)

plt.title("Missing Values Heatmap", fontsize=16, pad=20)
plt.show()

"""# **Train-Test Split**"""

from sklearn.model_selection import train_test_split

X = df_encoded.drop(columns=['Churn'])
y = df_encoded['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

import numpy as np

print("\nClass distribution in y:")
print("Original:", np.unique(y, return_counts=True))
print("Train:", np.unique(y_train, return_counts=True))
print("Test:", np.unique(y_test, return_counts=True))

"""# **Supervised Models**"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report, precision_score, recall_score, roc_auc_score, ConfusionMatrixDisplay


models = {
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)



    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='weighted')
    precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    # AUC
    try:
        y_prob = model.predict_proba(X_test)[:, 1]
        auc = roc_auc_score(y_test, y_prob)
    except:
        auc = None


    results.append((name, acc, precision, recall, f1, auc))
    results_df = pd.DataFrame(results, columns=['Model', 'Accuracy', 'Precision', 'Recall', 'F1-score', 'AUC'])

    print(f"\n{name} Results:")
    print("Accuracy:", acc)
    print("F1 Score:", f1)
    print("Precision:", precision)
    print("Recall:", recall)
    print("AUC:", auc)
    print("Classification Report:\n", classification_report(y_test, y_pred))

    # Plot Confusion Matrix
    disp = ConfusionMatrixDisplay.from_estimator(model, X_test, y_test, cmap='Blues', values_format='d')
    disp.figure_.suptitle(f"{name} - Confusion Matrix")
    plt.show()

"""# **Comparison Plot**"""

#Supervised Model Performance Comparison
results_df.set_index('Model')[['Accuracy', 'Precision', 'Recall', 'F1-score']].plot(
    kind='bar', figsize=(10,6), rot=0, colormap='coolwarm'
)
plt.title("Supervised Model Performance Comparison")
plt.ylabel("Score")
plt.ylim(0,1.1)
plt.show()

"""# **ROC Curves**"""

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc


plt.figure(figsize=(8, 5))

for name, model in models.items():
    if hasattr(model, "predict_proba"):
        y_score = model.predict_proba(X_test)[:, 1]
    else:
        y_score = model.decision_function(X_test)
    fpr, tpr, _ = roc_curve(y_test, y_score)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1],)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve (Binary Classification)')
plt.legend()
plt.show()

"""# **Unsupervised Learning (KMeans with Silhouette Score)**"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

num_cols = ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']
cat_cols = [col for col in df_encoded.columns if col not in num_cols + ['Churn']]

preprocessing = ColumnTransformer([
    ('num', StandardScaler(), num_cols),
    ('cat', 'passthrough', cat_cols)
])

kmeans_pipeline = Pipeline([
    ('preprocessing', preprocessing),
    ('kmeans', KMeans(n_clusters=3, random_state=42, n_init="auto"))
])

X_all = df_encoded.drop('Churn', axis=1)
kmeans_pipeline.fit(X_all)

clusters = kmeans_pipeline.named_steps['kmeans'].labels_
df_encoded['Cluster'] = clusters

sil_score = silhouette_score(preprocessing.fit_transform(X_all), clusters)
print(f"Silhouette Score: {sil_score:.4f}")


df_encoded['Cluster'].value_counts().plot(kind='bar', color=['skyblue','orange','green'])
plt.title("Number of Samples per Cluster")
plt.xlabel("Cluster")
plt.ylabel("Count")
plt.show()

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from collections import Counter
from sklearn.preprocessing import StandardScaler

preprocess = StandardScaler()

kmeans_k = 2
RANDOM_STATE = 42

kmeans_pipe = Pipeline(steps=[("prep", preprocess),
                              ("kmeans", KMeans(n_clusters=kmeans_k, random_state=RANDOM_STATE, n_init="auto"))])
kmeans_pipe.fit(X)
km_labels = kmeans_pipe.named_steps["kmeans"].labels_
print("Cluster counts:", Counter(km_labels))

X_prep = kmeans_pipe.named_steps["prep"].fit_transform(X)
if X_prep.shape[1] >= 2:
    pca = PCA(n_components=2, random_state=RANDOM_STATE)
    pts = pca.fit_transform(X_prep)
    plt.figure()
    plt.scatter(pts[:,0], pts[:,1], c=km_labels, s=12)
    plt.title("KMeans clusters (PCA 2D)"); plt.xlabel("PC1"); plt.ylabel("PC2")
    plt.tight_layout(); plt.show()

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

print("Explained variance ratio:", pca.explained_variance_ratio_)
print("PCA components (loadings):\n", pca.components_)

feature_names = X.columns
loading_df = pd.DataFrame(pca.components_, columns=feature_names, index=["PC1", "PC2"])
print(loading_df)

"""# **Before Clustering (True Labels)**"""

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris


iris = load_iris()
X = iris.data
y = iris.target

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(8, 6))
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y, cmap='viridis', s=50)
plt.title('Iris Dataset Before Clustering (True Labels)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.colorbar(label='True Label (Species)')
plt.tight_layout()
plt.show()

"""# **After Clustering (KMeans Clustering)**"""

from sklearn.cluster import KMeans
from collections import Counter
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt


KMEANS_K = 3
RANDOM_STATE = 42


kmeans_pipe = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("kmeans", KMeans(n_clusters=KMEANS_K, random_state=RANDOM_STATE, n_init="auto"))
])


kmeans_pipe.fit(X)


km_labels = kmeans_pipe.named_steps["kmeans"].labels_
print("Cluster counts:", Counter(km_labels))


X_pca_clusters = pca.fit_transform(X_scaled)


plt.figure(figsize=(8, 6))
plt.scatter(X_pca_clusters[:, 0], X_pca_clusters[:, 1], c=km_labels, cmap='viridis', s=50)
plt.title(f'Iris Dataset After KMeans Clustering (K={KMEANS_K})')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.colorbar(label='Cluster Label')
plt.tight_layout()
plt.show()